version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'friday'
      time: '16:00'
      timezone: 'Europe/Warsaw'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'friday'
      time: '16:00'
      timezone: 'Europe/Warsaw'
