name: 'Continuous Integration'
on: pull_request

jobs:
  basics:
    name: 'Static tests and build'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2.3.4

      # Beginning of yarn setup, keep in sync between all workflows
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Use cached node_modules'
        id: cache-modules
        uses: actions/cache@v2.1.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: 'Find location of global yarn cache'
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: 'Cache global yarn cache'
        uses: actions/cache@v2.1.5
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Install dependency'
        run: yarn install --frozen-lockfile
      # End of yarn setup

      - name: 'Audit dependencies'
        run: /bin/sh -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'
      - name: 'Run Prettier'
        run: yarn prettier
      - name: 'Run ESLint'
        run: yarn lint
      - name: 'Run StyleLint'
        run: yarn stylelint
      - name: 'Run Type check'
        run: yarn type-check
      - name: 'Build API'
        run: cd packages/api && yarn build
      - name: 'Build Client'
        run: cd packages/client && yarn build

  tests:
    name: 'Unit and E2E tests'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NODE_ENV: 'test'
      DB_PORT: 5432
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres_password
      DB_DATABASE_TEST: smart_gate_db_test
      TEST_USER_EMAIL: 'joe.doe@gmail.com'
      TEST_USER_PASSWORD: '@12345Aa'
      TEST_USER_FIRSTNAME: 'Joe'
      TEST_USER_LASTNAME: 'Doe'
      ETHEREAL_USER: ${{ secrets.ETHEREAL_USER }}
      ETHEREAL_PASSWORD: ${{ secrets.ETHEREAL_PASSWORD }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2.3.4

      # Beginning of yarn setup, keep in sync between all workflows
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Use cached node_modules'
        id: cache-modules
        uses: actions/cache@v2.1.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: 'Find location of global yarn cache'
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: 'Cache global yarn cache'
        uses: actions/cache@v2.1.5
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Install dependency'
        run: yarn install --frozen-lockfile
      # End of yarn setup

      - name: 'Setup test database'
        run: cd packages/ci-scripts && yarn setup:testDB
      - name: 'Run unit tests'
        run: yarn test
      - name: 'Run E2E tests'
        uses: cypress-io/github-action@v2
        with:
          project: ./packages/e2e
          start: yarn start:ci
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          record: true
          spec: packages/e2e/src/**/*.spec.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: 'x4q1ri'
          PORT: 8080
          API_PORT: 3030
          REACT_APP_API_URL: 'http://localhost:3030'
          CLIENT_URL: 'http://localhost:8080'
          COOKIE_SECRET: '1234'
          ACCESS_SECRET: '1234'
          REFRESH_SECRET: '1234'
          LOGOUT_SECRET: '1234'
